### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Coronon**
Fixed grammar, wording, spelling and layout

### CODE REVIEW

**Comment by Coronon** [comment]
OMG first it tells me to add two spaces, now it wants them removed!

**Comment by Coronon** [comment]
Officially no clue what it wants me to do, even my markdownlinter in VS Code cant figure it out.

**Comment by EmlJnke** [comment]
Oh great now I have a perfect readme in a project nobody will ever really care about xd

**Comment by Coronon** [comment]
Sounds perfect to me 😂

**Pull request merged**
